### ISSUE TITLE
What about adding this to maven repository?

### ISSUE THREAD

**Issue by akellataken** [olxmute/mapstruct-kotlin-builder-generator#1]
I'd really like to use it in my project, it would be cool, if I could you it as a dependency.

Thanks for what you are doing!

**Comment by olxmute** [comment]
Hi, @akellanotavailable, thank you for your feedback, it's very important to me.
Now you can add library using kapt in Gradle:
```groovy
kapt("io.github.olxmute:mapstruct-kotlin-builder-generator:0.0.2")
```
or Maven
```xml
<annotationProcessorPath>
   <groupId>io.github.olxmute</groupId>
   <artifactId>mapstruct-kotlin-builder-generator</artifactId>
   <version>0.0.2</version>
</annotationProcessorPath>
```
